# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 414eb0a916f9e22387d3dd05d0369e48a85faa589a390ce20e31dd795a92f263dbc7e7b70806ec302501236cb1dcb37c5cb409929ffa611b841f10a2c8e709b5

test:
  secret_key_base: cf4b9d50f2e85b2bc24e606076b21b179fcefb1395cd69edae61d001f3c56082c8cf5163c173e85aa15e2a76b3cc6a8c53f84ac06c114bfaf35348217cc7d521

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
